/* GENERATED by scripts/gen-island-bootstrap.mjs from
 * packages/runtime/src/island-js/builtin-exports.json — do not edit by
 * hand.
 *
 * The named export lists for the builtins the Rust island's bootstrap
 * registers, so `import { x } from "node:y"` LINKS. A builtin outside
 * this table gets the default-only wrapper, and its require raises the
 * island's does-not-provide throw at evaluation. */

/// Named exports per shimmed builtin, mirroring the C island's
/// `isl_builtins`.
static ISLAND_BUILTIN_EXPORTS: [(&str, &str); 24] = [
    ("node:events", "EventEmitter,once,on,listenerCount,getEventListeners,setMaxListeners,defaultMaxListeners,errorMonitor,captureRejectionSymbol"),
    ("node:path", "sep,delimiter,basename,dirname,extname,join,resolve,normalize,relative,isAbsolute,toNamespacedPath,parse,format,posix,win32"),
    ("node:path/posix", "sep,delimiter,basename,dirname,extname,join,resolve,normalize,relative,isAbsolute,toNamespacedPath,parse,format,posix,win32"),
    ("node:path/win32", "sep,delimiter,basename,dirname,extname,join,resolve,normalize,relative,isAbsolute,toNamespacedPath,parse,format,posix,win32"),
    ("node:diagnostics_channel", "channel,subscribe,unsubscribe,hasSubscribers,tracingChannel"),
    ("node:module", "createRequire,builtinModules,isBuiltin,syncBuiltinESMExports,register,findSourceMap"),
    ("node:buffer", "Buffer,SlowBuffer,INSPECT_MAX_BYTES,kMaxLength,kStringMaxLength,constants,isAscii,isUtf8,atob,btoa,Blob,File,transcode,resolveObjectURL"),
    ("node:string_decoder", "StringDecoder"),
    ("node:stream", "Stream,Readable,Writable,Duplex,Transform,PassThrough,pipeline,finished,addAbortSignal,promises,isErrored,isDestroyed,isReadable,isWritable"),
    ("node:stream/promises", "pipeline,finished"),
    ("node:stream/consumers", "text,buffer,arrayBuffer,json,blob"),
    ("node:stream/web", "ReadableStream,WritableStream,TransformStream,TextEncoderStream,TextDecoderStream,CountQueuingStrategy,ByteLengthQueuingStrategy,ReadableStreamDefaultReader,ReadableStreamDefaultController,WritableStreamDefaultWriter"),
    ("node:assert", "AssertionError,ok,fail,equal,notEqual,strictEqual,notStrictEqual,deepEqual,notDeepEqual,deepStrictEqual,notDeepStrictEqual,throws,doesNotThrow,rejects,doesNotReject,match,doesNotMatch,ifError,strict"),
    ("node:assert/strict", "AssertionError,ok,fail,equal,notEqual,strictEqual,notStrictEqual,deepEqual,notDeepEqual,deepStrictEqual,notDeepStrictEqual,throws,doesNotThrow,rejects,doesNotReject,match,doesNotMatch,ifError,strict"),
    ("node:util", "format,formatWithOptions,inspect,inherits,promisify,callbackify,deprecate,debuglog,debug,types,isDeepStrictEqual,stripVTControlCharacters,styleText,parseArgs,toUSVString,_extend,TextEncoder,TextDecoder,isArray"),
    ("node:util/types", "isAnyArrayBuffer,isArrayBufferView,isArgumentsObject,isArrayBuffer,isAsyncFunction,isBigInt64Array,isBigUint64Array,isBooleanObject,isBoxedPrimitive,isBigIntObject,isCryptoKey,isDataView,isDate,isExternal,isFloat16Array,isFloat32Array,isFloat64Array,isGeneratorFunction,isGeneratorObject,isInt8Array,isInt16Array,isInt32Array,isKeyObject,isMap,isMapIterator,isModuleNamespaceObject,isNativeError,isNumberObject,isPromise,isProxy,isRegExp,isSet,isSetIterator,isSharedArrayBuffer,isStringObject,isSymbolObject,isTypedArray,isUint8Array,isUint8ClampedArray,isUint16Array,isUint32Array,isWeakMap,isWeakSet"),
    ("node:async_hooks", "AsyncLocalStorage,AsyncResource,executionAsyncId,triggerAsyncId,executionAsyncResource,createHook"),
    ("node:domain", "create,createDomain,Domain,active"),
    ("node:perf_hooks", "performance,PerformanceObserver,monitorEventLoopDelay,constants"),
    ("node:v8", "startupSnapshot,cachedDataVersionTag,getHeapStatistics,getHeapSpaceStatistics,getHeapCodeStatistics,getCppHeapStatistics,setFlagsFromString,takeCoverage,stopCoverage,setHeapSnapshotNearHeapLimit,serialize,deserialize,writeHeapSnapshot,getHeapSnapshot,queryObjects,startCpuProfile,isStringOneByteRepresentation,promiseHooks,Serializer,Deserializer,DefaultSerializer,DefaultDeserializer,GCProfiler"),
    ("node:punycode", "version,ucs2,decode,encode,toASCII,toUnicode"),
    ("node:querystring", "parse,stringify,decode,encode,escape,unescape,unescapeBuffer"),
    ("node:console", "Console,log,info,debug,warn,error,trace,dir,assert,count,countReset,time,timeEnd,group,groupEnd,table,clear"),
    ("node:process", "argv,env,platform,execPath,execArgv,version,versions,stdout,stderr,stdin,cwd,exit,nextTick,hrtime,pid,ppid,title,argv0,release,config,allowedNodeEnvironmentFlags,emitWarning,uptime,memoryUsage,umask,exitCode,on,once,off,removeListener,emit"),
];
