/* GENERATED by scripts/gen-island-bootstrap.mjs.
 * C island exports are owned by @internal/compatibility; Rust retains its
 * engine-specific export table below. */
#ifndef SCR_ISLAND_BUILTINS_H
#define SCR_ISLAND_BUILTINS_H
#include "scr_island_manifest.h"
#endif
