import type { RustDynamicContext } from "./dynamic-context.js";
import type { RustClosureShape } from "./model.js";

export function emitRustDynamicEquality(context: RustDynamicContext, boxedShapes: readonly RustClosureShape[]): void {
  const name = context.dynTypeName();
  const usesEmbeddedModules = context.hasEmbeddedModules();
  context.line(`fn sc_dyn_equal(left: &${name}, right: &${name}, deep: bool) -> bool {`);
  context.pushIndent();
  context.line("if let (Some(left), Some(right)) = (sc_dyn_function_identity(left), sc_dyn_function_identity(right)) { return left == right; }");
  context.line(`if let (${name}::Proxy(left), ${name}::Proxy(right)) = (left, right) { if left.ptr_eq(right) { return true; } }`);
  context.line(`if deep && (matches!(left, ${name}::Proxy(..)) || matches!(right, ${name}::Proxy(..))) { return sc_dyn_proxy_unsupported("deep equality"); }`);
  context.line(`if deep && matches!(left, ${name}::Effect(..)) || deep && matches!(right, ${name}::Effect(..)) { return sc_dyn_effect_reflection("deep equality"); }`);
  context.line("match (left, right) {");
  context.pushIndent();
  context.line(`(${name}::Undefined, ${name}::Undefined) | (${name}::Null, ${name}::Null) => true,`);
  context.line(`(${name}::Number(left), ${name}::Number(right)) => runtime::number_same_value(*left, *right),`);
  context.line(`(${name}::Boolean(left), ${name}::Boolean(right)) => left == right,`);
  context.line(`(${name}::Effect(left), ${name}::Effect(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::Date(left), ${name}::Date(right)) => left == right || (deep && { let a = runtime::date_value_time(left); let b = runtime::date_value_time(right); a == b || (runtime::target_runtime_id() != "bun" && a.is_nan() && b.is_nan()) }),`);
  context.line(`(${name}::BigInt(left), ${name}::BigInt(right)) => left == right,`);
  context.line(`(${name}::Symbol(left), ${name}::Symbol(right)) => runtime::symbol_ptr_eq(left, right),`);
  context.line(`(${name}::String(left), ${name}::String(right)) => left.as_ref() == right.as_ref(),`);
  if (usesEmbeddedModules) context.line(`(${name}::Island(left), ${name}::Island(right)) => runtime::island_strict_equal(left, right),`);
  context.line(`(${name}::Regex(left), ${name}::Regex(right)) => std::rc::Rc::ptr_eq(left, right),`);
  context.line(`(${name}::Url(left), ${name}::Url(right)) => std::rc::Rc::ptr_eq(left, right),`);
  context.line(`(${name}::Promise(left), ${name}::Promise(right)) => runtime::promise_handle_identity(left) == runtime::promise_handle_identity(right),`);
  context.line(`(${name}::NetServer(left), ${name}::NetServer(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::NetSocket(left), ${name}::NetSocket(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::AbortController(left), ${name}::AbortController(right)) | (${name}::AbortSignal(left), ${name}::AbortSignal(right)) => left.ptr_eq(right), (${name}::HttpRequest(left), ${name}::HttpRequest(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::HttpHeaders(left), ${name}::HttpHeaders(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::FetchBody(left), ${name}::FetchBody(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::WebStream(left), ${name}::WebStream(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::WebController(left), ${name}::WebController(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::WebReader(left), ${name}::WebReader(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::FetchReader(left), ${name}::FetchReader(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::HttpResponse(left), ${name}::HttpResponse(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::HttpAgent(left), ${name}::HttpAgent(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::Bytes(left), ${name}::Bytes(right)) => {`);
  context.pushIndent();
  context.line("if left.ptr_eq(right) { true } else if !deep || runtime::bytes_len(left) != runtime::bytes_len(right) { false } else {");
  context.pushIndent();
  context.line("let mut index = 0.0; let mut equal = true; while equal && index < runtime::bytes_len(left) { equal = runtime::bytes_get(left, index) == runtime::bytes_get(right, index); index += 1.0; } equal");
  context.popIndent();
  context.line("}");
  context.popIndent();
  context.line("},");
  context.line(`(${name}::TypedBytes(left), ${name}::TypedBytes(right)) => runtime::typed_bytes_ptr_eq(left, right) || (deep && runtime::typed_bytes_deep_equals(left, right)),`);
  context.line(`(${name}::Buffer(left), ${name}::Buffer(right)) => left.ptr_eq(right) || (deep && runtime::bytes_deep_equals(left, right)),`);
  context.line(`(${name}::NativeConstructor(left), ${name}::NativeConstructor(right)) => left == right,`);
  context.line(`(${name}::NativeMethod(left), ${name}::NativeMethod(right)) => left == right,`);
  context.line(`(${name}::ArrayIterator(left), ${name}::ArrayIterator(right)) => left.ptr_eq(right),`);
  context.line(`(${name}::Array(left), ${name}::Array(right)) => {`);
  context.pushIndent();
  context.line("if runtime::array_ptr_eq(left, right) { true } else if !deep || runtime::array_len(left) != runtime::array_len(right) { false } else {");
  context.pushIndent();
  context.line("let mut index = 0.0; let mut equal = true; while equal && index < runtime::array_len(left) { equal = sc_dyn_equal(&runtime::array_get(left, index), &runtime::array_get(right, index), true); index += 1.0; } equal");
  context.popIndent();
  context.line("}");
  context.popIndent();
  context.line("},");
  context.line(`(${name}::Object(left), ${name}::Object(right)) => {`);
  context.pushIndent();
  context.line("if sc_dyn_is_null_proto(left) != sc_dyn_is_null_proto(right) { false } else if runtime::map_ptr_eq(left, right) { true } else if !deep || runtime::map_size(left) != runtime::map_size(right) { false } else {");
  context.pushIndent();
  context.line("let mut index = 0.0; let mut equal = true; while equal && index < runtime::map_iter_count(left) { if runtime::map_iter_live(left, index) { let key = runtime::map_iter_key(left, index); let field = runtime::map_iter_value(left, index); equal = runtime::map_get_by(right, &key, |a, b| a.as_ref() == b.as_ref()).is_some_and(|other| sc_dyn_equal(&field, &other, true)); } index += 1.0; } equal");
  context.popIndent();
  context.line("}");
  context.popIndent();
  context.line("},");
  for (const shape of boxedShapes) {
    const variant = context.dynFunctionVariant(shape);
    context.line(`(${name}::${variant}(left, _, _), ${name}::${variant}(right, _, _)) => left.identity() == right.identity(),`);
  }
  context.line("_ => false,");
  context.popIndent();
  context.line("}");
  context.popIndent();
  context.line("}");
}
