import type { RustDynamicContext } from "./dynamic-context.js";

export function emitRustDynamicObjectWalk(context: RustDynamicContext): void {
  const name = context.dynTypeName();
  const functionVariants = [...context.dynBoxedFunctionShapes]
    .flatMap((key) => {
      const shape = context.closureShapes.get(key);
      return shape === undefined ? [] : [context.dynFunctionVariant(shape)];
    })
    .filter((variant, index, variants) => variants.indexOf(variant) === index);
  context.line(`fn sc_dyn_obj_walk_push(output: &runtime::JsArray<${name}>, mode: u8, key: runtime::JsString, value: ${name}) {`);
  context.pushIndent();
  context.line("let item = match mode {");
  context.pushIndent();
  context.line(`0 => ${name}::String(key),`);
  context.line("1 => value,");
  context.line(`_ => ${name}::Array(runtime::array_new(vec![${name}::String(key), value])),`);
  context.popIndent();
  context.line("};");
  context.line("runtime::array_push(output, item);");
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_obj_walk(value: &${name}, mode: u8) -> ${name} {`);
  context.pushIndent();
  context.line(`let output: runtime::JsArray<${name}> = runtime::array_new(Vec::new());`);
  context.line("match value {");
  context.pushIndent();
  context.line(`${name}::Undefined | ${name}::Null => runtime::throw_type_error("Cannot convert undefined or null to object".to_owned()),`);
  context.line(`${name}::Object(object) => for (key, field) in runtime::map_string_entries_js_order(object) { sc_dyn_obj_walk_push(&output, mode, key, field); },`);
  context.line(`${name}::Array(array) => {`);
  context.pushIndent();
  context.line("let mut index = 0usize;");
  context.line("while index < runtime::array_len(array) as usize {");
  context.pushIndent();
  context.line("sc_dyn_obj_walk_push(&output, mode, runtime::string(&index.to_string()), runtime::array_get(array, index as f64));");
  context.line("index += 1;");
  context.popIndent();
  context.line("}");
  context.popIndent();
  context.line("},");
  context.line(`${name}::Bytes(bytes) | ${name}::Buffer(bytes) => {`);
  context.pushIndent();
  context.line("let mut index = 0usize;");
  context.line("while index < runtime::bytes_len(bytes) as usize {");
  context.pushIndent();
  context.line(`sc_dyn_obj_walk_push(&output, mode, runtime::string(&index.to_string()), ${name}::Number(runtime::bytes_get(bytes, index as f64)));`);
  context.line("index += 1;");
  context.popIndent();
  context.line("}");
  context.popIndent();
  context.line("},");
  context.line(`${name}::TypedBytes(bytes) => { let mut index = 0usize; while index < runtime::typed_bytes_len(bytes) as usize { sc_dyn_obj_walk_push(&output, mode, runtime::string(&index.to_string()), ${name}::Number(runtime::typed_bytes_get(bytes, index as f64))); index += 1; } },`);
  context.line(`${name}::String(text) => for (index, character) in text.chars().enumerate() {`);
  context.pushIndent();
  context.line(`sc_dyn_obj_walk_push(&output, mode, runtime::string(&index.to_string()), ${name}::String(runtime::string(&character.to_string())));`);
  context.popIndent();
  context.line("},");
  context.line("_ => {},");
  context.popIndent();
  context.line("}");
  context.line(`${name}::Array(output)`);
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_obj_keys(value: &${name}) -> ${name} { sc_dyn_obj_walk(value, 0) }`);
  context.line(`fn sc_dyn_obj_values(value: &${name}) -> ${name} { sc_dyn_obj_walk(value, 1) }`);
  context.line(`fn sc_dyn_obj_entries(value: &${name}) -> ${name} { sc_dyn_obj_walk(value, 2) }`);
  context.line(`fn sc_dyn_assign_map(target: &runtime::JsMap<runtime::JsString, ${name}>, source: &runtime::JsMap<runtime::JsString, ${name}>) {`);
  context.pushIndent();
  context.line("let mut index = 0.0;");
  context.line("while index < runtime::map_iter_count(source) {");
  context.pushIndent();
  context.line("if runtime::map_iter_live(source, index) { let key = runtime::map_iter_key(source, index); let value = runtime::map_iter_value(source, index); runtime::map_set_by(target, key, value, |left, right| left.as_ref() == right.as_ref()); }");
  context.line("index += 1.0;");
  context.popIndent();
  context.line("}");
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_assign_from(target: &${name}, source: &${name}) {`);
  context.pushIndent();
  context.line("let target = match target {");
  context.pushIndent();
  context.line(`${name}::Object(target) => target,`);
  for (const variant of functionVariants) context.line(`${name}::${variant}(_, _, properties) => properties,`);
  context.line("_ => return,");
  context.popIndent();
  context.line("};");
  context.line("match source {");
  context.pushIndent();
  context.line(`${name}::Object(source) => sc_dyn_assign_map(target, source),`);
  for (const variant of functionVariants) {
    context.line(`${name}::${variant}(_, _, properties) => sc_dyn_assign_map(target, properties),`);
  }
  context.line(`${name}::Array(source) => { let mut index = 0.0; while index < runtime::array_len(source) { runtime::map_set_by(target, runtime::string(&(index as usize).to_string()), runtime::array_get(source, index), |left, right| left.as_ref() == right.as_ref()); index += 1.0; } },`);
  context.line(`${name}::Bytes(source) => { let mut index = 0.0; while index < runtime::bytes_len(source) { runtime::map_set_by(target, runtime::string(&(index as usize).to_string()), ${name}::Number(runtime::bytes_get(source, index)), |left, right| left.as_ref() == right.as_ref()); index += 1.0; } },`);
  context.line(`${name}::TypedBytes(source) => { let mut index = 0.0; while index < runtime::typed_bytes_len(source) { runtime::map_set_by(target, runtime::string(&(index as usize).to_string()), ${name}::Number(runtime::typed_bytes_get(source, index)), |left, right| left.as_ref() == right.as_ref()); index += 1.0; } },`);
  context.line(`${name}::Buffer(source) => { let mut index = 0.0; while index < runtime::bytes_len(source) { runtime::map_set_by(target, runtime::string(&(index as usize).to_string()), ${name}::Number(runtime::bytes_get(source, index)), |left, right| left.as_ref() == right.as_ref()); index += 1.0; } },`);
  context.line(`${name}::String(source) => for (index, character) in source.chars().enumerate() { runtime::map_set_by(target, runtime::string(&index.to_string()), ${name}::String(runtime::string(&character.to_string())), |left, right| left.as_ref() == right.as_ref()); },`);
  context.line("_ => {},");
  context.popIndent();
  context.line("}");
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_assign(target: &${name}, source: &${name}) -> ${name} {`);
  context.pushIndent();
  context.line(`if matches!(target, ${name}::Undefined | ${name}::Null) { runtime::throw_type_error("Cannot convert undefined or null to object".to_owned()); }`);
  context.line("sc_dyn_assign_from(target, source);");
  context.line("target.clone()");
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_pack_push(pack: &${name}, value: ${name}) {`);
  context.pushIndent();
  context.line(`let ${name}::Array(pack) = pack else { unreachable!("scriptc invariant: dynamic argument pack is not an array"); };`);
  context.line("runtime::array_push(pack, value);");
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_pack_push_spread(pack: &${name}, source: &${name}, what: &runtime::JsString, iterated: bool) {`);
  context.pushIndent();
  context.line("match source {");
  context.pushIndent();
  context.line(`${name}::Array(source) => { let ${name}::Array(pack) = pack else { unreachable!() }; runtime::array_extend(pack, source); return; },`);
  context.line(`${name}::Bytes(source) => { let mut index = 0.0; while index < runtime::bytes_len(source) { sc_dyn_pack_push(pack, ${name}::Number(runtime::bytes_get(source, index))); index += 1.0; } return; },`);
  context.line(`${name}::TypedBytes(source) => { let mut index = 0.0; while index < runtime::typed_bytes_len(source) { sc_dyn_pack_push(pack, ${name}::Number(runtime::typed_bytes_get(source, index))); index += 1.0; } return; },`);
  context.line(`${name}::Buffer(source) => { let mut index = 0.0; while index < runtime::bytes_len(source) { sc_dyn_pack_push(pack, ${name}::Number(runtime::bytes_get(source, index))); index += 1.0; } return; },`);
  context.line(`${name}::String(source) => { for character in source.chars() { sc_dyn_pack_push(pack, ${name}::String(runtime::string(&character.to_string()))); } return; },`);
  context.line("_ => {},");
  context.popIndent();
  context.line("}");
  context.line("if !iterated {");
  context.pushIndent();
  context.line(`if matches!(source, ${name}::Undefined | ${name}::Null) { let property = if matches!(source, ${name}::Undefined) { "undefined" } else { "null" }; runtime::throw_type_error(format!("{what} is not iterable (cannot read property {property})")); }`);
  context.line('runtime::throw_type_error("Spread syntax requires ...iterable[Symbol.iterator] to be a function".to_owned());');
  context.popIndent();
  context.line("}");
  context.line("if !what.is_empty() { runtime::throw_type_error(what.to_string()); }");
  context.line("let description = match source {");
  context.pushIndent();
  context.line(`${name}::Undefined => "undefined".to_owned(),`);
  context.line(`${name}::Null => "object null".to_owned(),`);
  context.line(`${name}::Number(value) => format!("number {}", runtime::display_number(*value)),`);
  context.line(`${name}::Boolean(value) => format!("boolean {}", runtime::display_bool(*value)),`);
  context.line("value if sc_dyn_kind(value) == \"function\" => \"function\".to_owned(),");
  context.line("_ => \"object\".to_owned(),");
  context.popIndent();
  context.line("};");
  context.line("runtime::throw_type_error(format!(\"{description} is not iterable (cannot read property Symbol(Symbol.iterator))\"))");
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_assign_all(target: &${name}, sources: &${name}) -> ${name} {`);
  context.pushIndent();
  context.line(`if matches!(target, ${name}::Undefined | ${name}::Null) { runtime::throw_type_error("Cannot convert undefined or null to object".to_owned()); }`);
  context.line(`if let ${name}::Array(sources) = sources { let mut index = 0.0; while index < runtime::array_len(sources) { let source = runtime::array_get(sources, index); sc_dyn_assign_from(target, &source); index += 1.0; } }`);
  context.line("target.clone()");
  context.popIndent();
  context.line("}");
}
