import type { RustDynamicContext } from "./dynamic-context.js";
import type { RustClosureShape } from "./model.js";
import { emitRustDynamicEquality } from "./dynamic-equality.js";

export function emitRustDynamicErrorAndCloneHelpers(context: RustDynamicContext, boxedShapes: readonly RustClosureShape[]): void {
  const name = context.dynTypeName();
  const usesEmbeddedModules = context.hasEmbeddedModules();
  const mapType = `runtime::JsMap<runtime::JsString, ${name}>`;
  const errorType = context.errorClassRoots().length === 0 ? "runtime::JsError" : context.errorValueName();
  const errorHelper = (helper: string): string => context.errorClassRoots().length === 0 ? `runtime::error_${helper}` : `sc_error_${helper}`;
  const errorTarget = context.errorClassRoots().length === 0 ? "target.strip_prefix('%').unwrap_or(target)" : "target";
  const abortError = context.errorClassRoots().length === 0 ? `runtime::dom_exception_new(runtime::string("This operation was aborted"), runtime::string("AbortError"), None)` : `${context.errorValueName()}::Builtin(runtime::dom_exception_new(runtime::string("This operation was aborted"), runtime::string("AbortError"), None))`;
  const timeoutError = context.errorClassRoots().length === 0 ? `runtime::dom_exception_new(runtime::string("The operation was aborted due to timeout"), runtime::string("TimeoutError"), None)` : `${context.errorValueName()}::Builtin(runtime::dom_exception_new(runtime::string("The operation was aborted due to timeout"), runtime::string("TimeoutError"), None))`;

  context.line("std::thread_local! {");
  context.pushIndent();
  context.line(`static SC_DYN_ERROR_CACHE: std::cell::RefCell<Vec<(usize, ${errorType}, ${mapType})>> = const { std::cell::RefCell::new(Vec::new()) };`);
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_error_box(error: &${errorType}) -> ${name} {`);
  context.pushIndent();
  context.line(`let identity = ${errorHelper("identity")}(error);`);
  context.line("if let Some(object) = SC_DYN_ERROR_CACHE.with(|cache| cache.borrow().iter().find(|(cached, _, _)| *cached == identity).map(|(_, _, object)| object.clone())) {");
  context.pushIndent();
  context.line(`return ${name}::Object(object);`);
  context.popIndent();
  context.line("}");
  context.line(`let object: ${mapType} = runtime::map_new();`);
  context.line("SC_DYN_ERROR_CACHE.with(|cache| cache.borrow_mut().push((identity, error.clone(), object.clone())));");
  context.line(`runtime::map_set_by(&object, runtime::string("%error"), ${name}::Boolean(true), |left, right| left.as_ref() == right.as_ref());`);
  context.line(`runtime::map_set_by(&object, runtime::string("name"), ${name}::String(${errorHelper("name")}(error)), |left, right| left.as_ref() == right.as_ref());`);
  context.line(`runtime::map_set_by(&object, runtime::string("message"), ${name}::String(${errorHelper("message")}(error)), |left, right| left.as_ref() == right.as_ref());`);
  context.line(`if ${errorHelper("is_class")}(error, "DOMException") {`);
  context.pushIndent();
  context.line(`runtime::map_set_by(&object, runtime::string("code"), ${name}::Number(${errorHelper("dom_code")}(error)), |left, right| left.as_ref() == right.as_ref());`);
  context.line(`if let Some(cause) = ${errorHelper("dom_cause")}::<${name}>(error) { runtime::map_set_by(&object, runtime::string("cause"), cause, |left, right| left.as_ref() == right.as_ref()); }`);
  context.popIndent();
  context.line(`} else if let Some(code) = ${errorHelper("code")}(error) {`);
  context.pushIndent();
  context.line(`runtime::map_set_by(&object, runtime::string("code"), ${name}::String(code), |left, right| left.as_ref() == right.as_ref());`);
  context.popIndent();
  context.line("}");
  context.line(`${name}::Object(object)`);
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_abort_default_reason() -> ${name} { let error = ${abortError}; sc_dyn_error_box(&error) }`);
  context.line(`fn sc_dyn_abort_timeout_reason() -> ${name} { let error = ${timeoutError}; sc_dyn_error_box(&error) }`);
  context.line(`fn sc_dyn_error_instanceof(value: &${name}, target: &str) -> bool {`);
  context.pushIndent();
  context.line(`let ${name}::Object(object) = value else { return false; };`);
  context.line("let identity = object.identity();");
  context.line(`SC_DYN_ERROR_CACHE.with(|cache| cache.borrow().iter().find(|(_, _, cached)| cached.identity() == identity).is_some_and(|(_, error, _)| ${errorHelper("is_class")}(error, ${errorTarget})))`);
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_error_unbox(value: ${name}) -> ${errorType} {`);
  context.pushIndent();
  // A realm Error handle (a typed callback's `Error` parameter, the
  // rejection of an engine promise): name and message copy out.
  if (context.hasEmbeddedModules()) {
    const caughtErrorTest = context.errorClassRoots().length === 0 ? "runtime::caught_is_error(&caught)" : "sc_caught_is_error_class(&caught, \"Error\")";
    const caughtErrorValue = context.errorClassRoots().length === 0 ? "runtime::caught_error_value(&caught)" : "sc_caught_error_value(&caught)";
    context.line(`if let ${name}::Island(handle) = &value { let caught = runtime::island_exit_error(handle); if ${caughtErrorTest} { return ${caughtErrorValue}; } return sc_dyn_check_fail("Error", &value); }`);
  }
  context.line(`let ${name}::Object(object) = &value else { return sc_dyn_check_fail("Error", &value); };`);
  context.line("let identity = object.identity();");
  context.line("SC_DYN_ERROR_CACHE.with(|cache| cache.borrow().iter().find(|(_, _, cached)| cached.identity() == identity).map(|(_, error, _)| error.clone())).unwrap_or_else(|| sc_dyn_check_fail(\"Error\", &value))");
  context.popIndent();
  context.line("}");
  context.line("fn sc_dyn_error_cache_clear() {");
  context.pushIndent();
  context.line("SC_DYN_ERROR_CACHE.with(|cache| cache.borrow_mut().clear());");
  context.popIndent();
  context.line("}");

  context.line(`fn sc_dyn_validate_clone_options(options: &${name}) {`);
  context.pushIndent();
  context.line(`if matches!(options, ${name}::Undefined | ${name}::Null) { return; }`);
  context.line(`if matches!(options, ${name}::Proxy(..)) { return sc_dyn_proxy_unsupported("structuredClone options reflection"); }`);
  context.line(`let ${name}::Object(object) = options else {`);
  context.pushIndent();
  context.line("runtime::throw_type_error_code(\"Failed to execute 'structuredClone': Options cannot be converted to a dictionary\".to_owned(), \"ERR_INVALID_ARG_TYPE\");");
  context.popIndent();
  context.line("};");
  context.line(`let transfer = runtime::map_get_by(object, &runtime::string("transfer"), |left, right| left.as_ref() == right.as_ref()).unwrap_or(${name}::Undefined);`);
  context.line(`if matches!(transfer, ${name}::Undefined) { return; }`);
  context.line(`let ${name}::Array(transfer) = transfer else {`);
  context.pushIndent();
  context.line("runtime::throw_type_error_code(\"Failed to execute 'structuredClone': transfer in Options cannot be converted to sequence.\".to_owned(), \"ERR_INVALID_ARG_TYPE\");");
  context.popIndent();
  context.line("};");
  context.line("if runtime::array_len(&transfer) > 0.0 { runtime::throw_dom_exception(\"DataCloneError\", \"Found invalid value in transferList.\"); }");
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_clone(value: &${name}, parents: &mut Vec<usize>) -> ${name} { sc_dyn_clone_dates(value, parents, &mut Vec::new()) }`);
  context.line(`fn sc_dyn_clone_dates(value: &${name}, parents: &mut Vec<usize>, dates: &mut Vec<(usize, runtime::JsDate)>) -> ${name} {`);
  context.pushIndent();
  context.line("match value {");
  context.pushIndent();
  context.line(`${name}::Undefined => ${name}::Undefined,`);
  context.line(`${name}::Null => ${name}::Null,`);
  context.line(`${name}::Number(value) => ${name}::Number(*value),`);
  context.line(`${name}::BigInt(value) => ${name}::BigInt(value.clone()),`);
  context.line(`${name}::Date(value) => { if runtime::target_runtime_id() == \"bun\" { return ${name}::Date(runtime::date_value_copy(value)); } let id = runtime::date_value_identity(value); if let Some((_, copied)) = dates.iter().find(|(key, _)| *key == id) { ${name}::Date(copied.clone()) } else { let copied = runtime::date_value_copy(value); dates.push((id, copied.clone())); ${name}::Date(copied) } },`);
  context.line(`${name}::Boolean(value) => ${name}::Boolean(*value),`);
  context.line(`${name}::String(value) => ${name}::String(value.clone()),`);
  context.line(`${name}::Regex(value) => ${name}::Regex(runtime::regex_new(&runtime::regex_source(value), &runtime::regex_flags(value))),`);
  context.line(`${name}::Url(value) => ${name}::Url(value.clone()),`);
  context.line(`${name}::Bytes(value) => ${name}::Bytes(runtime::bytes_copy(value)),`);
  context.line(`${name}::TypedBytes(value) => ${name}::TypedBytes(runtime::typed_bytes_copy(value)),`);
  context.line(`${name}::Buffer(value) => ${name}::Buffer(runtime::bytes_copy(value)),`);
  context.line(`${name}::NativeConstructor(name) => ${name}::NativeConstructor(name),`);
  context.line(`${name}::NativeMethod(method) => runtime::throw_dom_exception("DataCloneError", &format!("{} could not be cloned.", method.name())),`);
  context.line(`${name}::Getter(..) => runtime::throw_dom_exception("DataCloneError", "getter could not be cloned."),`);
  context.line(`${name}::Effect(..) => sc_dyn_effect_reflection("structuredClone"),`);
  context.line(`${name}::Symbol(value) => runtime::throw_dom_exception("DataCloneError", &format!("{} could not be cloned.", runtime::symbol_to_string(value))),`);
  context.line(`${name}::Proxy(..) => runtime::throw_dom_exception("DataCloneError", "#<Object> could not be cloned."),`);
  context.line(`${name}::Promise(..) => runtime::throw_dom_exception("DataCloneError", "#<Promise> could not be cloned."),`);
  context.line(`${name}::NetServer(..) => runtime::throw_dom_exception("DataCloneError", "#<Server> could not be cloned."),`);
  context.line(`${name}::NetSocket(..) => runtime::throw_dom_exception("DataCloneError", "#<Socket> could not be cloned."),`);
  context.line(`${name}::AbortController(..) => runtime::throw_dom_exception("DataCloneError", "#<AbortController> could not be cloned."), ${name}::AbortSignal(..) => runtime::throw_dom_exception("DataCloneError", "#<AbortSignal> could not be cloned."), ${name}::HttpRequest(..) => runtime::throw_dom_exception("DataCloneError", "#<IncomingMessage> could not be cloned."),`);
  context.line(`${name}::HttpHeaders(..) => runtime::throw_dom_exception("DataCloneError", "#<Headers> could not be cloned."),`);
  context.line(`${name}::FetchBody(..) => runtime::throw_dom_exception("DataCloneError", "#<ReadableStream> could not be cloned."),`);
  context.line(`${name}::WebStream(..) => runtime::throw_dom_exception("DataCloneError", "#<ReadableStream> could not be cloned."),`);
  context.line(`${name}::WebController(..) => runtime::throw_dom_exception("DataCloneError", "#<ReadableStreamDefaultController> could not be cloned."),`);
  context.line(`${name}::WebReader(..) => runtime::throw_dom_exception("DataCloneError", "#<ReadableStreamDefaultReader> could not be cloned."),`);
  context.line(`${name}::FetchReader(..) => runtime::throw_dom_exception("DataCloneError", "#<ReadableStreamDefaultReader> could not be cloned."),`);
  context.line(`${name}::HttpResponse(..) => runtime::throw_dom_exception("DataCloneError", "#<ServerResponse> could not be cloned."),`);
  context.line(`${name}::HttpAgent(..) => runtime::throw_dom_exception("DataCloneError", "#<Agent> could not be cloned."),`);
  context.line(`${name}::ArrayIterator(..) => runtime::throw_dom_exception("DataCloneError", "#<Array Iterator> could not be cloned."),`);
  if (usesEmbeddedModules) context.line(`${name}::Island(..) => runtime::throw_dom_exception("DataCloneError", "embedded JavaScript value could not be cloned."),`);
  context.line(`${name}::Array(value) => {`);
  context.pushIndent();
  context.line("let identity = value.identity();");
  context.line("if parents.contains(&identity) { runtime::throw_value(runtime::error_new(\"Error\", runtime::string(\"structuredClone of cyclic values (the checked-dynamic tree cannot represent cycles) is not supported yet\"))); }");
  context.line("parents.push(identity);");
  context.line(`let output: runtime::JsArray<${name}> = runtime::array_new(Vec::new());`);
  context.line("let mut index = 0.0;");
  context.line("while index < runtime::array_len(value) { let field = runtime::array_get(value, index); runtime::array_push(&output, sc_dyn_clone_dates(&field, parents, dates)); index += 1.0; }");
  context.line("parents.pop();");
  context.line(`${name}::Array(output)`);
  context.popIndent();
  context.line("},");
  context.line(`${name}::Object(value) => {`);
  context.pushIndent();
  context.line("if runtime::map_is_module_namespace(value) { runtime::throw_dom_exception(\"DataCloneError\", \"[object Module] could not be cloned.\"); }");
  context.line("let identity = value.identity();");
  context.line("if parents.contains(&identity) { runtime::throw_value(runtime::error_new(\"Error\", runtime::string(\"structuredClone of cyclic values (the checked-dynamic tree cannot represent cycles) is not supported yet\"))); }");
  context.line("parents.push(identity);");
  context.line(`let output: ${mapType} = runtime::map_new();`);
  context.line("let mut index = 0.0;");
  context.line("while index < runtime::map_iter_count(value) {");
  context.pushIndent();
  context.line("if runtime::map_iter_live(value, index) { let key = runtime::map_iter_key(value, index); let field = runtime::map_iter_value(value, index); runtime::map_set_by(&output, key, sc_dyn_clone_dates(&field, parents, dates), |left, right| left.as_ref() == right.as_ref()); }");
  context.line("index += 1.0;");
  context.popIndent();
  context.line("}");
  context.line("parents.pop();");
  context.line(`${name}::Object(output)`);
  context.popIndent();
  context.line("},");
  if (boxedShapes.length > 0) {
    const patterns = boxedShapes.map((shape) => `${name}::${context.dynFunctionVariant(shape)}(..)`).join(" | ");
    context.line(`value @ (${patterns}) => runtime::throw_dom_exception("DataCloneError", &format!("{} could not be cloned.", sc_dyn_to_string(value))),`);
  }
  context.popIndent();
  context.line("}");
  context.popIndent();
  context.line("}");
  context.line(`fn sc_dyn_structured_clone(value: &${name}, options: &${name}) -> ${name} {`);
  context.pushIndent();
  context.line("sc_dyn_validate_clone_options(options);");
  context.line("sc_dyn_clone(value, &mut Vec::new())");
  context.popIndent();
  context.line("}");

  emitRustDynamicEquality(context, boxedShapes);
}
