// The context every Rust expression sub-emitter sees: the emitter's
// surface as one interface (split from expressions.ts so the class and
// its contract each stay under the file-line cap).
import type { IrFamily } from "../../ir/nodes.js";
import type { IrClassDef, IrExpr, IrFfiImport, IrFunction, IrLibCallback, IrRecordShape, IrStmt, IrType, IrUnionDef, SrcLoc } from "../../ir/nodes.js";
import type { IrFuncType, RustClassMeta, RustClosureShape, RustVtSlot } from "./model.js";
export interface RustExpressionContext {
  readonly chainValues: Map<string, string>;
  readonly classMeta: ReadonlyMap<string, RustClassMeta>;
  readonly closureShapes: ReadonlyMap<string, RustClosureShape>;
  readonly dynBoxedFunctionShapes: ReadonlySet<string>;
  readonly functions: ReadonlyMap<string, IrFunction>;
  ffiImports(): readonly IrFfiImport[];
  libraryCallbacks(): readonly IrLibCallback[];
  readonly records: ReadonlyMap<string, IrRecordShape>;
  nextName(prefix: string): string;
  currentFunction(): IrFunction | null;
  emitSequence(statements: readonly IrStmt[], emitResult: () => string): string;
  assignmentExpr(id: string, value: string, loc: SrcLoc): string;
  classAllocation(meta: RustClassMeta, args: readonly string[], loc: SrcLoc): string;
  classDef(name: string, loc?: SrcLoc): IrClassDef;
  classFieldName(className: string, fieldName: string, loc?: SrcLoc): string;
  classFieldStorageName(owner: RustClassMeta, fieldName: string): string;
  classMetaOf(name: string, loc?: SrcLoc): RustClassMeta;
  classStructName(name: string, loc?: SrcLoc): string;
  classSubtree(meta: RustClassMeta): RustClassMeta[];
  closureName(shape: RustClosureShape): string;
  closureShapeForType(type: IrFuncType, loc?: SrcLoc): RustClosureShape;
  defaultValue(type: IrType, loc: SrcLoc): string;
  displayExpr(expr: IrExpr): string;
  dynFunctionVariant(shape: RustClosureShape): string;
  dynTypeName(): string;
  emitArrayIntrinsic(expr: Extract<IrExpr, { kind: "arrIntrinsic" }>): string;
  emitBinary(expr: Extract<IrExpr, { kind: "bin" }>): string;
  emitBytesNewValue(expr: Extract<IrExpr, { kind: "bytesNew" }>, source: string | null): string;
  emitCallValue(expr: Extract<IrExpr, { kind: "callValue" }>): string;
  emitClosure(expr: Extract<IrExpr, { kind: "closure" }>): string;
  emitFamilyClosure(expr: Extract<IrExpr, { kind: "familyClosure" }>): string;
  emitCallFamily(expr: Extract<IrExpr, { kind: "callFamily" }>): string;
  emitClosureDispatch(callee: string, type: IrFuncType, args: string[], loc: SrcLoc): string;
  emitEventEmitterCall(expr: Extract<IrExpr, { kind: "libCall" }>): string | null;
  emitEventEmitterUpcast(value: string, source: IrType, loc: SrcLoc): string | null;
  emitEventEmitterDowncast(value: string, source: IrType, target: IrType, loc: SrcLoc): string | null;
  emitEventEmitterInstanceOf(value: string, source: IrType, target: string, loc: SrcLoc): string | null;
  emitDynCheckValue(type: IrType, value: string, loc?: SrcLoc): string;
  emitDynFromValue(type: IrType, value: string, loc?: SrcLoc, functionName?: string, liveRef?: boolean): string;
  emitFileHandleTransferPromise(expr: Extract<IrExpr, { kind: "libCall" }>): string;
  emitFsRenameCallback(expr: Extract<IrExpr, { kind: "libCall" }>): string;
  emitMapIntrinsic(expr: Extract<IrExpr, { kind: "mapIntrinsic" }>): string;
  emitOrDefault(expr: Extract<IrExpr, { kind: "orDefault" }>): string;
  emitPromiseFromSync(args: readonly IrExpr[], operation: (value: (index: number) => string) => string): string;
  emitPromiseRaceValue(from: IrType, to: IrType, value: string, loc: SrcLoc): string;
  emitRead(id: string, type: IrType, loc: SrcLoc): string;
  emitRecordCloneInitial(expr: Extract<IrExpr, { kind: "recordClone" }>, source: string): string;
  emitRecordCloneOverride(expr: Extract<IrExpr, { kind: "recordClone" }>, clone: string, name: string, value: string): string;
  emitSetIntrinsic(expr: Extract<IrExpr, { kind: "setIntrinsic" }>): string;
  emitStatements(statements: readonly IrStmt[]): void;
  emitToStringValue(type: IrType, operand: string, loc: SrcLoc): string;
  errorClassRoots(): RustClassMeta[];
  errorValueName(): string;
  errorValueVariant(meta: RustClassMeta): string;
  hierarchyFields(root: RustClassMeta): { owner: RustClassMeta; field: IrClassDef["fields"][number] }[];
  hasEmbeddedModules(): boolean;
  isEdgeValue(type: IrType): boolean;
  isRustJsonCompatible(type: IrType, visiting?: Set<string>): boolean;
  isUnit(type: IrType): boolean;
  mapKeyEquality(left: string, right: string, type: IrType, loc: SrcLoc): string;
  mapStoredKey(value: string, type: IrType): string;
  needsClone(type: IrType): boolean;
  numberLiteral(value: number): string;
  promiseRejectorVariant(type: IrFuncType, promiseType: IrType, loc?: SrcLoc): string;
  runtimeErrorAncestor(name: string): string | null;
  runtimeErrorIsA(source: string, target: string): boolean;
  rustString(value: string): string;
  rustType(type: IrType, loc?: SrcLoc): string;
  stripCasts(expr: IrExpr): IrExpr;
  truthiness(value: string, type: IrType, loc: SrcLoc): string;
  union(id: string, loc?: SrcLoc): IrUnionDef;
  unionEqName(id: string): string;
  unionName(id: string): string;
  familyName(id: string, loc?: SrcLoc): string;
  familyOf(id: string, loc?: SrcLoc): IrFamily;
  familyTargetOf(name: string): IrFamily | undefined;
  unionVariant(tag: number): string;
  unsupported(kind: string, loc?: SrcLoc): never;
  virtualImplementation(meta: RustClassMeta, slot: RustVtSlot): IrFunction;
}
