import { DATE_T, F64, STRING } from "./nodes.js";

export const DATE_LIB_FN_SIGS = {
  "date.now": { argTypes: [], result: F64 },
  "date.newNow": { argTypes: [], result: DATE_T },
  "date.newMs": { argTypes: [F64], result: DATE_T },
  "date.newString": { argTypes: [STRING], result: DATE_T },
  "date.newComponents": { argTypes: [F64, F64, F64, F64, F64, F64, F64], result: DATE_T },
  "date.getTime": { argTypes: [DATE_T], result: F64 },
  "date.valueOf": { argTypes: [DATE_T], result: F64 },
  "date.toISOString": { argTypes: [F64], result: STRING },
  "date.toISOStringValue": { argTypes: [DATE_T], result: STRING },
  "date.getFullYear": { argTypes: [DATE_T], result: F64 },
  "date.getUTCFullYear": { argTypes: [DATE_T], result: F64 },
  "date.getMonth": { argTypes: [DATE_T], result: F64 },
  "date.getUTCMonth": { argTypes: [DATE_T], result: F64 },
  "date.getDate": { argTypes: [DATE_T], result: F64 },
  "date.getUTCDate": { argTypes: [DATE_T], result: F64 },
  "date.getDay": { argTypes: [DATE_T], result: F64 },
  "date.getUTCDay": { argTypes: [DATE_T], result: F64 },
  "date.getHours": { argTypes: [DATE_T], result: F64 },
  "date.getUTCHours": { argTypes: [DATE_T], result: F64 },
  "date.getMinutes": { argTypes: [DATE_T], result: F64 },
  "date.getUTCMinutes": { argTypes: [DATE_T], result: F64 },
  "date.getSeconds": { argTypes: [DATE_T], result: F64 },
  "date.getUTCSeconds": { argTypes: [DATE_T], result: F64 },
  "date.getMilliseconds": { argTypes: [DATE_T], result: F64 },
  "date.getUTCMilliseconds": { argTypes: [DATE_T], result: F64 },
  "date.getTimezoneOffset": { argTypes: [DATE_T], result: F64 },
  "date.parseGetTime": { argTypes: [STRING], result: F64 },
  "date.utc": { argTypes: [F64, F64, F64, F64, F64, F64, F64], result: F64 },
};
