import type { IrType } from "./ir.js";

export const BIGINT: IrType = { kind: "bigint" };
export const F64: IrType = { kind: "f64" };
export const DATE_T: IrType = { kind: "date" };
export const BYTES_U8: IrType = { kind: "bytes", elem: "u8" };
export const STRING: IrType = { kind: "string" };
export const BOOL: IrType = { kind: "bool" };
export const REGEX: IrType = { kind: "regex" };
export const URL_T: IrType = { kind: "url" };
export const SEARCH_PARAMS_T: IrType = { kind: "searchParams" };
export const SYMBOL_T: IrType = { kind: "symbol" };
export const STATS_T: IrType = { kind: "stats" };
export const FILEHANDLE_T: IrType = { kind: "fileHandle" };
export const SPAWNRES_T: IrType = { kind: "spawnRes" };
export const CHILD_T: IrType = { kind: "child" }; export const EFFECT_T: IrType = { kind: "effect" };
export const SQLITE_DB_T: IrType = { kind: "sqliteDb" }; export const SQLITE_STMT_T: IrType = { kind: "sqliteStmt" };
export const NETSERVER_T: IrType = { kind: "netServer" };
export const NETSOCKET_T: IrType = { kind: "netSocket" };
export const HTTP2SESSION_T: IrType = { kind: "http2Session" };
export const HTTP2STREAM_T: IrType = { kind: "http2Stream" };
export const DGRAMSOCK_T: IrType = { kind: "dgramSocket" };
export const TESTCTX_T: IrType = { kind: "testCtx" };
export const HTTPREQ_T: IrType = { kind: "httpReq" };
export const HTTPRES_T: IrType = { kind: "httpRes" };
export const HTTPCLIENTREQ_T: IrType = { kind: "httpClientReq" };
export const SECURECTX_T: IrType = { kind: "secureCtx" };
export const FSWATCHER_T: IrType = { kind: "fsWatcher" };
export const CHILDSTREAM_T: IrType = { kind: "childStream" };
export const PROCSTREAM_T: IrType = { kind: "procStream" };
export const VOID: IrType = { kind: "void" };
export const DYN: IrType = { kind: "dyn" };
export const JSVAL: IrType = { kind: "jsval" };
export const CAUGHT: IrType = { kind: "caught" };
export const UNDEFINED_T: IrType = { kind: "undefinedT" };
export const NULL_T: IrType = { kind: "nullT" };
